# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc8fe59eac52bb9bbd9e2568dcda5bbd4d2f4b284fe2cab0c5c9af4a28bbbd86cc464ec095b883a3b85c3cd66b4e3cef1e35c836a564d8f7cd8d6d517aa48dcc

test:
  secret_key_base: 8605dbf769b98b391c3f5aac846d44f3e03bd3f9d472d90486bbbc14b04fcbfe6024bf11c12b7f48a9ffa2a862fa023da5554eb83ba10e5515d1c36e097b0259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
